### ISSUE TITLE
Generated data layout and usage instructions

### ISSUE THREAD

**Issue by bfloriang** [Cleafy/promqueen#2]
Hi there,

I've been playing around with promrec and promfill after finding a reference on (https://github.com/prometheus/prometheus/issues/535) but I'm struggling to get the tools working for me. 

I notice that the directory and file layout that results from running promplay looks different than an empty Prometheus data store just created by bringing Prometheus up (I tried version 1.7.1 and 1.8.2).

**After running Promplay:**
```
[XXX@XXX data]$ tree
.
├── archived_fingerprint_to_metric
│   ├── 000002.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   └── MANIFEST-000003
├── archived_fingerprint_to_timerange
│   ├── 000002.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   └── MANIFEST-000003
├── DIRTY
├── heads.db
├── labelname_to_labelvalues
│   ├── 000001.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   └── MANIFEST-000000
├── labelpair_to_fingerprints
│   ├── 000001.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   └── MANIFEST-000000
└── VERSION
```

**Fresh Prometheus installation**
```
/prometheus/data # ls *

99:
6bf7c4f0744d30.db  81c763c5f4d943.db  8d67781712ca9b.db  a0d965e6535daf.db  b394c82595132c.db  eb84fea15ae0a8.db  f4b4c142823c09.db

9a:
54201d6ae73552.db  6806be24a5ce00.db

de:
0e7d051f319666.db  f43a6192e1be9c.db

df:
02d74982a0fffa.db  10cbca521ed1cd.db  17a83d5b652ca7.db  5a507fbaf0dfc3.db  a23eb2338abee9.db  aaa3bb99297f27.db  aaf0e130a90c18.db  e4f026f3b83be1.db  f8b3d8510ca802.db
```

It would be much appretiated if you could show an example of filling the database with random metrics (or give a description how to) and then show where to map the resulting data stores on an existing Prometheus installation.

**Comment by thypon** [comment]
As seen here https://github.com/Cleafy/promqueen/blob/master/Gopkg.toml#L38 the prometheus database generated is in 1.5.3. It should be possible to use the latest 1.x.x prometheus series without any problem, but the output database after the import could have another format.

I think I will update the prometheus library soon in order to support natively 1.9 and 2.0 series.

**Comment by thypon** [comment]
```
node_exporter &
promrec.elf -i 10s -u node-exporter=http://localhost:9100/metrics
```

Then hit Ctrl-C after some time

If you start a <=1.8.2 `prometheus` version inside the current directory it is possible to inspect the results. I run with the `prometheus` command, without any other parameter. It is possible to change the data retention time in `promplay` and prometheus respectively. `promplay` help and README.md shows the default.

```
      --storage.retention-period=360h
                             Period of time to store data for
      --storage.checkpoint-interval=30m
                             Period of time to store data for
```

**Comment by carlosflorencio** [comment]
Sorry to ask here, but this tool supports the latest version of Prometheus (v2.x)?

If not, is it easy to upgrade it?

Thanks

**Comment by Sessa93** [comment]
@carlosflorencio Currently Promqueen does not offer support for Prometheus 2.x
The upgrade may not be easy. We are planning to release a new version that supports it, but I can not give you a strict deadline.

**Comment by lstanczak** [comment]
Do you have any new info about Prometheus 2 compatible version. Is it still planned to be developed?

**Comment by Sessa93** [comment]
Hello @lstanczak, we are not planning to develop it in the near future. If you or anyone else in the community  wanna try an implementation, i will be happy to review the PR.

**Comment by singh9vj** [comment]
Hi,

Does this tool supports 2.15.X version of prometheus now?
