### ISSUE TITLE
cannot find package "github.com/prometheus/prometheus/storage/local

### ISSUE THREAD

**Issue by albert-huang** [Cleafy/promqueen#3]
hello, i am getting error message when use go get for brand new install. should I revert back to some historical version of prometheus, or i miss sth. (sorry very new to golang)

    $ go get github.com/Cleafy/promqueen/bin/promplay
    package github.com/prometheus/prometheus/storage/local: cannot find package "github.com/prometheus/prometheus/storage/local"

checking prometheus storage folder i do not see any file as "local*" too.
my platform ubuntu 16.04.3 LTS x86_64, i try both go version 1.6 (ubuntu apt repository), and go1.9.1.

thanks

**Comment by parry84** [comment]
Hello, the Prometheus local storage has been removed in Prometheus 2.0.
I'm changing the imports to a frozen fork of Prometheus repo in order to have the project building.

**Comment by albert-huang** [comment]
thank you very much for reply. the local package issue fixed. but the dependency seems more than that. some common package still having trouble too, error message as:

```shell
src/github.com/Cleafy/promqueen/bin/promplay/main.go:227:35: cannot use s (type 
*"github.com/prometheus/common/model".Sample) as type *"github.com/Cleafy/
prometheus/vendor/github.com/prometheus/common/model".
Sample in argument to sampleAppender.Append
```

promrec do not have any issue.

**Comment by impimp** [comment]
+1

**Comment by parry84** [comment]
Hello, currently PromQueen does not support Prometheus 2.x and we have no plan to support it a the moment.

To solve the building issue we propose a new procedure based on 'go dep', which is the official Go dependency management tool (see the README).
